0:
    0:
        - "⛔ Well, that didn't work."
        - You press the START button. Nothing happens. Have you collected
        - all of the necessary parts scattered throughout the ship?
1:
    0:
        - "🚀 Success!"
        - The engine begins to faintly glow and, as with all sufficiently
        - advanced technologies, you're not really sure it's working. But,
        - you think it is. Head to the bridge find out.
