- description: Starship engine started (run ./Engine)
  check: MatchCommandFragment
  options:
    fragment: "1"
    count: 1
    exact: true
    command: jq .engine_started .flags
- description: Rocket achieved liftoff (run ./Console)
  check: MatchCommandFragment
  options:
    fragment: "1"
    count: 1
    exact: true
    command: jq .liftoff .flags
- description: Keypad functions and returns an output (even if not correct)
  check: MatchCommandFragment
  options:
    fragment: "true"
    count: 1
    exact: true
    command: jq .keycode .flags
- description: Keypad returns the correct output
  check: MatchCommandFragment
  options:
    fragment: "2.0"
    count: 1
    exact: true
    command: 'python -c "from bridge.Keypad import Keypad; k = Keypad(); k.entered = 1414; print(k.decode(1414))"'
- bridge/Keypad.py:
    - description: Keypad uses an add instruction
      check: MatchFileRegex
      options:
        regex: '[a-z0-9_]+(\s+)?(\+\=|\+)(\s+)?[a-z0-9_]+'
        count: 1
        exact: true
    - description: Keypad uses a multiply instruction
      check: MatchFileRegex
      options:
        regex: '[a-z0-9_]+(\s+)?(\*\=|\*)(\s+)?[a-z0-9_]+'
        count: 1
        exact: true
    - description: Keypad uses a subtract instruction
      check: MatchFileRegex
      options:
        regex: '[a-z0-9_]+(\s+)?(\-\=|\-)(\s+)?[a-z0-9_]+'
        count: 1
        exact: true
    - description: Keypad uses a divide instruction
      check: MatchFileRegex
      options:
        regex: '[a-z0-9_]+(\s+)?[\\\=](\s+)?[a-z0-9_]+'
        count: 2
        exact: false
