- description: Starship engine started (run ./Engine)
  check: MatchCommandFragment
  options:
    fragment: "1"
    count: 1
    exact: true
    command: jq .engine_started .flags
- description: Rocket achieved liftoff (run ./Console)
  check: MatchCommandFragment
  options:
    fragment: "1"
    count: 1
    exact: true
    command: jq .liftoff .flags
