0:
    0:
        -         /\
        -        /  \
        -       /    \
        -      /______\
        -     |        |
        -     |        |
        -     |        |
        -     |        |
        -     |        |
        -     |        |
        -    /|   ||   |\
        -   / |   ||   | \
        -  /  |   ||   |  \
        - /___|   ||   |___\
        -     |        |
        -      \      /
        -       ||  ||
1:
    0:
        - Nope.
