#!/usr/bin/env python

import os
import sys
import narrator
import gitit

from narrator import Checkpoint

n = narrator.Narrator()

if Checkpoint.check_flag("engine_started"):
    n.path.change({
        "act": 0,
        "scene": 1
    })
    Checkpoint.set_flag("liftoff")
    if not os.path.exists("Keypad.py"):
        n.path.change({
            "act": 1,
            "scene": 0
        })
        gitit.get(
            "https://cdn.githubraw.com/hellowhorl/whorl-objects/main/",
            "space-junk",
            "Keypad.py"
        )

n.narrate()
