name: Tasks complete
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        if: always()
      - name: Setup Python
        if: always()
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.10.6
      - name: Set up grading environment
        run: |
          sudo apt-get update
          sudo apt install jq
          sudo apt install --only-upgrade python3-pip
          sudo python -m pip install gatorgrade --ignore-installed PyYAML
          sudo python -m pip install yq
      - name: Check startship progress
        run: |
            gatorgrade --config .gatorgrader.yml
